name: Docker Image CI

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version number
        id: version
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "::set-output name=version::$VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            juyangjia5/iphoto:latest
            juyangjia5/iphoto:${{ steps.version.outputs.version }}
